//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: dds_builtinTopics.h
//  Source: ../../../../etc/idl/dds_builtinTopics.idl
//  Generated: Tue Apr 15 14:15:23 2014
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _DDS_BUILTINTOPICS_H_
#define _DDS_BUILTINTOPICS_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"
#include "sacpp_if.h"


namespace DDS
{
   struct Duration_t;
   struct UserDataQosPolicy;
   struct TopicDataQosPolicy;
   struct GroupDataQosPolicy;
   struct TransportPriorityQosPolicy;
   struct LifespanQosPolicy;
   struct DurabilityQosPolicy;
   struct PresentationQosPolicy;
   struct DeadlineQosPolicy;
   struct LatencyBudgetQosPolicy;
   struct OwnershipQosPolicy;
   struct OwnershipStrengthQosPolicy;
   struct LivelinessQosPolicy;
   struct TimeBasedFilterQosPolicy;
   struct PartitionQosPolicy;
   struct ReliabilityQosPolicy;
   struct DestinationOrderQosPolicy;
   struct HistoryQosPolicy;
   struct ResourceLimitsQosPolicy;
   struct DurabilityServiceQosPolicy;
   struct ParticipantBuiltinTopicData;
   struct TopicBuiltinTopicData;
   struct PublicationBuiltinTopicData;
   struct SubscriptionBuiltinTopicData;
   struct octSeq_uniq_ {};
   typedef DDS_DCPSUFLSeq < Octet, struct octSeq_uniq_> octSeq;
   typedef DDS_DCPSSequence_var < octSeq> octSeq_var;
   typedef DDS_DCPSSequence_out < octSeq> octSeq_out;
   typedef DDS::Long BuiltinTopicKey_t_slice;
   typedef DDS::Long BuiltinTopicKey_t[3];
   typedef BuiltinTopicKey_t BuiltinTopicKey_t_out;
   SACPP_API extern BuiltinTopicKey_t_slice * BuiltinTopicKey_t_alloc ();
   SACPP_API extern void BuiltinTopicKey_t_free (BuiltinTopicKey_t_slice *);
   SACPP_API extern void BuiltinTopicKey_t_copy (BuiltinTopicKey_t_slice* to, const BuiltinTopicKey_t_slice* from);
   SACPP_API extern BuiltinTopicKey_t_slice *BuiltinTopicKey_t_dup (const BuiltinTopicKey_t_slice* from);

   struct BuiltinTopicKey_t_uniq_ {};
   typedef DDS_DCPS_FArray_var< BuiltinTopicKey_t, BuiltinTopicKey_t_slice, struct BuiltinTopicKey_t_uniq_> BuiltinTopicKey_t_var;
   typedef DDS_DCPS_Array_forany< BuiltinTopicKey_t, BuiltinTopicKey_t_slice, struct BuiltinTopicKey_t_uniq_> BuiltinTopicKey_t_forany;
   struct StringSeq_uniq_ {};
   typedef DDS_DCPSUStrSeqT <struct StringSeq_uniq_> StringSeq;
   typedef DDS_DCPSUStrSeq_var < StringSeq> StringSeq_var;
   typedef DDS_DCPSUStrSeq_out < StringSeq> StringSeq_out;

   struct SACPP_API Duration_t
   {
         Long sec;
         ULong nanosec;
   };

   typedef DDS_DCPSStruct_var < Duration_t> Duration_t_var;
   typedef Duration_t&Duration_t_out;

   struct SACPP_API UserDataQosPolicy
   {
         octSeq value;
   };

   typedef DDS_DCPSStruct_var < UserDataQosPolicy> UserDataQosPolicy_var;
   typedef DDS_DCPSStruct_out < UserDataQosPolicy> UserDataQosPolicy_out;

   struct SACPP_API TopicDataQosPolicy
   {
         octSeq value;
   };

   typedef DDS_DCPSStruct_var < TopicDataQosPolicy> TopicDataQosPolicy_var;
   typedef DDS_DCPSStruct_out < TopicDataQosPolicy> TopicDataQosPolicy_out;

   struct SACPP_API GroupDataQosPolicy
   {
         octSeq value;
   };

   typedef DDS_DCPSStruct_var < GroupDataQosPolicy> GroupDataQosPolicy_var;
   typedef DDS_DCPSStruct_out < GroupDataQosPolicy> GroupDataQosPolicy_out;

   struct SACPP_API TransportPriorityQosPolicy
   {
         Long value;
   };

   typedef DDS_DCPSStruct_var < TransportPriorityQosPolicy> TransportPriorityQosPolicy_var;
   typedef TransportPriorityQosPolicy&TransportPriorityQosPolicy_out;

   struct SACPP_API LifespanQosPolicy
   {
         Duration_t duration;
   };

   typedef DDS_DCPSStruct_var < LifespanQosPolicy> LifespanQosPolicy_var;
   typedef LifespanQosPolicy&LifespanQosPolicy_out;
   enum DurabilityQosPolicyKind
   {
      VOLATILE_DURABILITY_QOS,
      TRANSIENT_LOCAL_DURABILITY_QOS,
      TRANSIENT_DURABILITY_QOS,
      PERSISTENT_DURABILITY_QOS
   };

   struct SACPP_API DurabilityQosPolicy
   {
         DurabilityQosPolicyKind kind;
   };

   typedef DDS_DCPSStruct_var < DurabilityQosPolicy> DurabilityQosPolicy_var;
   typedef DurabilityQosPolicy&DurabilityQosPolicy_out;
   enum PresentationQosPolicyAccessScopeKind
   {
      INSTANCE_PRESENTATION_QOS,
      TOPIC_PRESENTATION_QOS,
      GROUP_PRESENTATION_QOS
   };

   struct SACPP_API PresentationQosPolicy
   {
         PresentationQosPolicyAccessScopeKind access_scope;
         Boolean coherent_access;
         Boolean ordered_access;
   };

   typedef DDS_DCPSStruct_var < PresentationQosPolicy> PresentationQosPolicy_var;
   typedef PresentationQosPolicy&PresentationQosPolicy_out;

   struct SACPP_API DeadlineQosPolicy
   {
         Duration_t period;
   };

   typedef DDS_DCPSStruct_var < DeadlineQosPolicy> DeadlineQosPolicy_var;
   typedef DeadlineQosPolicy&DeadlineQosPolicy_out;

   struct SACPP_API LatencyBudgetQosPolicy
   {
         Duration_t duration;
   };

   typedef DDS_DCPSStruct_var < LatencyBudgetQosPolicy> LatencyBudgetQosPolicy_var;
   typedef LatencyBudgetQosPolicy&LatencyBudgetQosPolicy_out;
   enum OwnershipQosPolicyKind
   {
      SHARED_OWNERSHIP_QOS,
      EXCLUSIVE_OWNERSHIP_QOS
   };

   struct SACPP_API OwnershipQosPolicy
   {
         OwnershipQosPolicyKind kind;
   };

   typedef DDS_DCPSStruct_var < OwnershipQosPolicy> OwnershipQosPolicy_var;
   typedef OwnershipQosPolicy&OwnershipQosPolicy_out;

   struct SACPP_API OwnershipStrengthQosPolicy
   {
         Long value;
   };

   typedef DDS_DCPSStruct_var < OwnershipStrengthQosPolicy> OwnershipStrengthQosPolicy_var;
   typedef OwnershipStrengthQosPolicy&OwnershipStrengthQosPolicy_out;
   enum LivelinessQosPolicyKind
   {
      AUTOMATIC_LIVELINESS_QOS,
      MANUAL_BY_PARTICIPANT_LIVELINESS_QOS,
      MANUAL_BY_TOPIC_LIVELINESS_QOS
   };

   struct SACPP_API LivelinessQosPolicy
   {
         LivelinessQosPolicyKind kind;
         Duration_t lease_duration;
   };

   typedef DDS_DCPSStruct_var < LivelinessQosPolicy> LivelinessQosPolicy_var;
   typedef LivelinessQosPolicy&LivelinessQosPolicy_out;

   struct SACPP_API TimeBasedFilterQosPolicy
   {
         Duration_t minimum_separation;
   };

   typedef DDS_DCPSStruct_var < TimeBasedFilterQosPolicy> TimeBasedFilterQosPolicy_var;
   typedef TimeBasedFilterQosPolicy&TimeBasedFilterQosPolicy_out;

   struct SACPP_API PartitionQosPolicy
   {
         StringSeq name;
   };

   typedef DDS_DCPSStruct_var < PartitionQosPolicy> PartitionQosPolicy_var;
   typedef DDS_DCPSStruct_out < PartitionQosPolicy> PartitionQosPolicy_out;
   enum ReliabilityQosPolicyKind
   {
      BEST_EFFORT_RELIABILITY_QOS,
      RELIABLE_RELIABILITY_QOS
   };

   struct SACPP_API ReliabilityQosPolicy
   {
         ReliabilityQosPolicyKind kind;
         Duration_t max_blocking_time;
         Boolean synchronous;
   };

   typedef DDS_DCPSStruct_var < ReliabilityQosPolicy> ReliabilityQosPolicy_var;
   typedef ReliabilityQosPolicy&ReliabilityQosPolicy_out;
   enum DestinationOrderQosPolicyKind
   {
      BY_RECEPTION_TIMESTAMP_DESTINATIONORDER_QOS,
      BY_SOURCE_TIMESTAMP_DESTINATIONORDER_QOS
   };

   struct SACPP_API DestinationOrderQosPolicy
   {
         DestinationOrderQosPolicyKind kind;
   };

   typedef DDS_DCPSStruct_var < DestinationOrderQosPolicy> DestinationOrderQosPolicy_var;
   typedef DestinationOrderQosPolicy&DestinationOrderQosPolicy_out;
   enum HistoryQosPolicyKind
   {
      KEEP_LAST_HISTORY_QOS,
      KEEP_ALL_HISTORY_QOS
   };

   struct SACPP_API HistoryQosPolicy
   {
         HistoryQosPolicyKind kind;
         Long depth;
   };

   typedef DDS_DCPSStruct_var < HistoryQosPolicy> HistoryQosPolicy_var;
   typedef HistoryQosPolicy&HistoryQosPolicy_out;

   struct SACPP_API ResourceLimitsQosPolicy
   {
         Long max_samples;
         Long max_instances;
         Long max_samples_per_instance;
   };

   typedef DDS_DCPSStruct_var < ResourceLimitsQosPolicy> ResourceLimitsQosPolicy_var;
   typedef ResourceLimitsQosPolicy&ResourceLimitsQosPolicy_out;

   struct SACPP_API DurabilityServiceQosPolicy
   {
         Duration_t service_cleanup_delay;
         HistoryQosPolicyKind history_kind;
         Long history_depth;
         Long max_samples;
         Long max_instances;
         Long max_samples_per_instance;
   };

   typedef DDS_DCPSStruct_var < DurabilityServiceQosPolicy> DurabilityServiceQosPolicy_var;
   typedef DurabilityServiceQosPolicy&DurabilityServiceQosPolicy_out;

   struct SACPP_API ParticipantBuiltinTopicData
   {
         BuiltinTopicKey_t key;
         UserDataQosPolicy user_data;
   };

   typedef DDS_DCPSStruct_var < ParticipantBuiltinTopicData> ParticipantBuiltinTopicData_var;
   typedef DDS_DCPSStruct_out < ParticipantBuiltinTopicData> ParticipantBuiltinTopicData_out;

   struct SACPP_API TopicBuiltinTopicData
   {
         BuiltinTopicKey_t key;
         String_mgr name;
         String_mgr type_name;
         DurabilityQosPolicy durability;
         DurabilityServiceQosPolicy durability_service;
         DeadlineQosPolicy deadline;
         LatencyBudgetQosPolicy latency_budget;
         LivelinessQosPolicy liveliness;
         ReliabilityQosPolicy reliability;
         TransportPriorityQosPolicy transport_priority;
         LifespanQosPolicy lifespan;
         DestinationOrderQosPolicy destination_order;
         HistoryQosPolicy history;
         ResourceLimitsQosPolicy resource_limits;
         OwnershipQosPolicy ownership;
         TopicDataQosPolicy topic_data;
   };

   typedef DDS_DCPSStruct_var < TopicBuiltinTopicData> TopicBuiltinTopicData_var;
   typedef DDS_DCPSStruct_out < TopicBuiltinTopicData> TopicBuiltinTopicData_out;

   struct SACPP_API PublicationBuiltinTopicData
   {
         BuiltinTopicKey_t key;
         BuiltinTopicKey_t participant_key;
         String_mgr topic_name;
         String_mgr type_name;
         DurabilityQosPolicy durability;
         DeadlineQosPolicy deadline;
         LatencyBudgetQosPolicy latency_budget;
         LivelinessQosPolicy liveliness;
         ReliabilityQosPolicy reliability;
         LifespanQosPolicy lifespan;
         DestinationOrderQosPolicy destination_order;
         UserDataQosPolicy user_data;
         OwnershipQosPolicy ownership;
         OwnershipStrengthQosPolicy ownership_strength;
         PresentationQosPolicy presentation;
         PartitionQosPolicy partition;
         TopicDataQosPolicy topic_data;
         GroupDataQosPolicy group_data;
   };

   typedef DDS_DCPSStruct_var < PublicationBuiltinTopicData> PublicationBuiltinTopicData_var;
   typedef DDS_DCPSStruct_out < PublicationBuiltinTopicData> PublicationBuiltinTopicData_out;

   struct SACPP_API SubscriptionBuiltinTopicData
   {
         BuiltinTopicKey_t key;
         BuiltinTopicKey_t participant_key;
         String_mgr topic_name;
         String_mgr type_name;
         DurabilityQosPolicy durability;
         DeadlineQosPolicy deadline;
         LatencyBudgetQosPolicy latency_budget;
         LivelinessQosPolicy liveliness;
         ReliabilityQosPolicy reliability;
         OwnershipQosPolicy ownership;
         DestinationOrderQosPolicy destination_order;
         UserDataQosPolicy user_data;
         TimeBasedFilterQosPolicy time_based_filter;
         PresentationQosPolicy presentation;
         PartitionQosPolicy partition;
         TopicDataQosPolicy topic_data;
         GroupDataQosPolicy group_data;
   };

   typedef DDS_DCPSStruct_var < SubscriptionBuiltinTopicData> SubscriptionBuiltinTopicData_var;
   typedef DDS_DCPSStruct_out < SubscriptionBuiltinTopicData> SubscriptionBuiltinTopicData_out;
}
template <>
DDS::BuiltinTopicKey_t_slice* DDS_DCPS_ArrayHelper < DDS::BuiltinTopicKey_t, DDS::BuiltinTopicKey_t_slice, DDS::BuiltinTopicKey_t_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < DDS::BuiltinTopicKey_t, DDS::BuiltinTopicKey_t_slice, DDS::BuiltinTopicKey_t_uniq_>::copy (DDS::BuiltinTopicKey_t_slice *to, const DDS::BuiltinTopicKey_t_slice* from);
template <>
void DDS_DCPS_ArrayHelper < DDS::BuiltinTopicKey_t, DDS::BuiltinTopicKey_t_slice, DDS::BuiltinTopicKey_t_uniq_>::free (DDS::BuiltinTopicKey_t_slice *ptr);




#endif 
