//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: dds_namedQosTypesDcps.h
//  Source: ../../../../src/api/dcps/sacpp/bld/x86_64.win64-release/dds_namedQosTypesDcps.idl
//  Generated: Tue Apr 15 14:15:30 2014
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _DDS_NAMEDQOSTYPESDCPS_H_
#define _DDS_NAMEDQOSTYPESDCPS_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"
#include "sacpp_if.h"
#include "dds_dcps.h"
#include "dds_dcps_builtintopics.h"
#include "dds_namedQosTypes.h"






#endif 
